version: '3'

services:
  jenkins:
    image: unpluggedkk/jenkins-with-data:v1
    ports:
      - 8080:8080
    volumes:
      - jenkins_home:/var/jenkins_home
    container_name: jenkins-container

  sonarqube:
    image: unpluggedkk/sonarqube-with-data:v1
    ports:
      - 9000:9000
    volumes:
      - sonarqube_data:/opt/sonarqube/data
    container_name: sonar-container

volumes:
  jenkins_home:
    driver: local
  sonarqube_data:
    driver: local
